export enum OrderStatus {
  PENDING = "PENDING",
  INVENTORY_RESERVED = "INVENTORY_RESERVED",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAID = "PAID",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
}
